# Generated by Django 6.0.2 on 2026-02-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
    ]
