# Generated by Django 6.0.2 on 2026-02-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_stripe_session_id_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=200, null=True, unique=True),
        ),
    ]
