# Generated by Django 6.0.2 on 2026-02-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Requested delivery/pickup time for preorders', null=True),
        ),
    ]
