# Generated by Django 4.2.27 on 2026-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_scheduled_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('wallet', 'Wallet'), ('online', 'Online Payment')], default='cash', max_length=20),
        ),
    ]
