# Generated by Django 6.0.2 on 2026-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=10.0, help_text='Fee for classroom/staffroom delivery', max_digits=6)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Disable new orders')),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
