# Generated by Django 6.0.2 on 2026-02-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_system_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.CharField(help_text='e.g. 03SU23FC071', max_length=20, unique=True)),
                ('is_registered', models.BooleanField(default=False, help_text='True if a user has already registered with this ID')),
            ],
        ),
    ]
