# Generated by Django 6.0.2 on 2026-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='upi_id',
            field=models.CharField(default='campusbites@ybl', help_text='Canteen UPI VPA', max_length=100),
        ),
    ]
