# Generated by Django 6.0.2 on 2026-02-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_systemsettings_upi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='e.g. 03SU26SI001 or 03SU26FI001', max_length=20, unique=True)),
                ('is_registered', models.BooleanField(default=False, help_text='True if a user has already registered with this ID')),
            ],
        ),
    ]
